### ISSUE TITLE
Exception while loading world: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by ManyStrongWords** [Devidian/docker-spaceengineers#13]
I keep encountering this error when trying to get the server running on the linux docker. The instance is experimental but not modded and runs fine on my windows computer. Anyone have any ideas?

**Comment by ManyStrongWords** [comment]
Log File
https://pastebin.com/CcKU0CG9

**Comment by Devidian** [comment]
Hi, i never encountered this, but maybe someone on the official discord has an answer? I dont think that this error only occures on this docker, maybe linux in general.
