### ISSUE TITLE
Getting disk write error without existing steamapps folder in game folder on installation.

### ISSUE THREAD

**Issue by NAHFE** [Devidian/docker-spaceengineers#16]
When installed or updating the server steamcmd gives out a "disk write error" and fails if there isn´t an existing steamapps folder inside the game folder.

Could easily be fixed by creating the folder in entrypoint.sh.

**Comment by Devidian** [comment]
A steamapps folder inside the game folder? Can you let us know how to reproduce this issue? Never occured to me.

**Comment by Devidian** [comment]
Seems to be self-solved: closing
