### ISSUE TITLE
Cant find the config files: No such file or directory

### ISSUE THREAD

**Issue by FlipperLP** [Devidian/docker-spaceengineers#17]
I sadly can't use it because the container is crashing right after these errors, not being able to find multiple config files.

I changed the path, to where the files should be stored on my host and the instance name, but left everything else in the `docker-compose.yml` as-is. (I'm using the precompiled docker image).

Any advice on how to fix this issue?

```se-server_1  | -------------------------------START------------------------------
se-server_1  | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
se-server_1  | Redirecting stderr to '/root/Steam/logs/stderr.txt'
se-server_1  | [  0%] Checking for available updates...
se-server_1  | [----] Verifying installation...
se-server_1  | Steam Console Client (c) Valve Corporation
se-server_1  | -- type 'quit' to exit --
se-server_1  | Loading Steam API...OK.
se-server_1  |
se-server_1  | Connecting anonymously to Steam Public...Logged in OK
se-server_1  | Waiting for user info...OK
se-server_1  | "@sSteamCmdForcePlatformType" = "windows"
se-server_1  | Success! App '298740' already up to date.
se-server_1  | grep: /appdata/space-engineers/instances/SomeName/SpaceEngineers-Dedicated.cfg: No such file or directory
se-server_1  | sed: can't read /appdata/space-engineers/instances/SomeName/SpaceEngineers-Dedicated.cfg: No such file or directory
se-server_1  | grep: /appdata/space-engineers/instances/SomeName/SpaceEngineers-Dedicated.cfg: No such file or directory
se-server_1  | sed: can't read /appdata/space-engineers/instances/SomeName/SpaceEngineers-Dedicated.cfg: No such file or directory
se-server_1  | --------------------------------END-------------------------------```

**Comment by Devidian** [comment]
Can you Provide your compose File too?

**Comment by FlipperLP** [comment]
nvm...  rtfm...
I'm quite new to hosting the game, so I wasn't aware that it needs to be pre-run locally in a torch server first. Ill to that now

**Comment by FlipperLP** [comment]
After some fiddling around, I finally got it to work, thanks for this awesome solution!

**Comment by ysm1mh** [comment]
> After some fiddling around, I finally got it to work, thanks for this awesome solution!

can you maybe tell others what you did to fix this?  i am running into the same issue and error about the no config file.
and i cant find what i am doing wrong.

i made a pre server setup with torch and copied the instance over to the instances folder.


any help would be helpfull

**Comment by FlipperLP** [comment]
Hi, yea, it was actually because I didn't read the manual. Aka RTFM.
Since this was a while ago. I only faintly remember what needed to be done, but the instructions can be seen here
https://github.com/Devidian/docker-spaceengineers#how-to-use

The mentioned program is not explained where, but you can probably find a tutorial on the webs somewhere.
