### ISSUE TITLE
Error: No IP assigned.

### ISSUE THREAD

**Issue by whodat** [Devidian/docker-spaceengineers#19]
Getting "Error: No IP assigned." about 50% of the time when starting the container. Server starts up normally if I do not get this error.  Not sure if it's related to the "dbus_connection_send_with_reply_and_block() were incorrect" warning above it.  

---------------------------------------------

00d4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\WINMM.dll" at 0xf6f0000: PE builtin
00d4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\dbghelp.dll" at 0x66200000: PE builtin
00d4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\imagehlp.dll" at 0x62740000: PE builtin
00d4:trace:loaddll:load_native_dll Loaded L"Z:\\appdata\\space-engineers\\SpaceEngineersDedicated\\DedicatedServer64\\tier0_s64.dll" at 0x13f000000: native
00d4:trace:loaddll:load_native_dll Loaded L"Z:\\appdata\\space-engineers\\SpaceEngineersDedicated\\DedicatedServer64\\vstdlib_s64.dll" at 0x13f600000: native
00d4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\MSWSOCK.dll" at 0x66800000: PE builtin
00d4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\dnsapi.dll" at 0x154891d10000: builtin
00d4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\netapi32.dll" at 0x154891d40000: builtin
00d4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\Secur32.dll" at 0x154891d90000: builtin
00d4:trace:loaddll:load_native_dll Loaded L"Z:\\appdata\\space-engineers\\SpaceEngineersDedicated\\DedicatedServer64\\steamclient64.dll" at 0x138000000: native
00d4:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00d4:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\Kerberos.dll" at 0x154891d00000: builtin
00d4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\api-ms-win-core-sysinfo-l1-2-1.dll" at 0xc940000: PE builtin
014c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\Wlanapi.dll" at 0x61480000: PE builtin
016c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\api-ms-win-appmodel-runtime-l1-1-1.dll" at 0x6dc00000: PE builtin
014c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\jsproxy.dll" at 0xf4a0000: PE builtin
014c:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\winhttp.dll" at 0x64340000: PE builtin
0170:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\dhcpcsvc.dll" at 0x70a00000: PE builtin
0078:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\iphlpapi.dll" at 0x15548fac0000: builtin
dbus[60]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.

This is normally a bug in some application using the D-Bus library.

D-Bus not built with -rdynamic so unable to print a backtrace
wine: Assertion failed at address 00001554905557BB (thread 0078), starting debugger...

0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\kernelbase.dll" at 0x120000: PE builtin
0180:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\kernel32.dll" at 0x7b410000: builtin
0180:trace:loaddll:load_so_dll Loaded L"4cpu.dll" at 0x149f652e0000: builtin
0180:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\winedbg.exe" at 0x149f65150000: builtin
0180:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\ucrtbase.dll" at 0x149f65030000: builtin
0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\dbghelp.dll" at 0x66200000: PE builtin
0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\sechost.dll" at 0x61900000: PE builtin
0180:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\advapi32.dll" at 0x149f64fa0000: builtin
0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\rpcrt4.dll" at 0x6fbc0000: PE builtin
0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\version.dll" at 0x65780000: PE builtin

0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\setupapi.dll" at 0x6a700000: PE builtin
0180:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\gdi32.dll" at 0x149f64b60000: builtin
0180:trace:loaddll:load_so_dll Loaded L"C:\\windows\\system32\\user32.dll" at 0x149f64d20000: builtin
0180:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\imm32.dll" at 0x6bec0000: PE builtin
0188:trace:loaddll:load_native_dll Loaded L"C:\\windows\\system32\\cryptnet.dll" at 0x67dc0000: PE builtin
2021-09-07 14:33:01.796: Error: No IP assigned.

00d4:trace:loaddll:load_native_dll Loaded L"C:\\windows\\Microsoft.NET\\Framework64\\v4.0.30319\\diasymreader.dll" at 0x6830000: native
--------------------------------END-------------------------------
00b0:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\drivers\\winebus.sys" : builtin
00b0:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\drivers\\wineusb.sys" : builtin
00b0:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\drivers\\winehid.sys" : builtin
00b0:trace:loaddll:free_modref Unloaded module L"C:\\windows\\system32\\hidclass.sys" : builtin

**Comment by anonymusdennis** [comment]
this is an normal error that often occurs
to fix it you wont need to do anything but restarting the server until it works (for me it was a max of 4 times and then all went good

**Comment by mmmaxwwwell** [comment]
@Devidian 😂 I like your style

**Comment by Devidian** [comment]
haha thank you man!

As a developer myself i hate those bugs that could be fixed in minutes and dont get fixed soon.

**Comment by Devidian** [comment]
I had to reopen it again https://support.keenswh.com/spaceengineers/pc/topic/23390-error-no-ip-assigned

**Comment by Craftsman96** [comment]
If you get the No IP error, go to your [SpaceEngineers-Dedicated.cfg], search for <RemoteApiEnabled>true</RemoteApiEnabled> and set it to false. fixed it for me

**Comment by Craftsman96** [comment]
So befor Serverstart Set IP in SpaceEngineers-Dedicated.cfg to 0.0.0.0 and RemoteApiEnabled to false.

**Comment by Devidian** [comment]
I've released a new image yesterday with wine 8, for me it seems as if that resolves the ip issue but can anyone confirm that?

NOTE: Currently there is a bug preventing the game from mod downloads. I've tried the fixes from discord but they did not work.

**Comment by Devidian** [comment]
Wine 8+ seems to fix that, i close this issue for now.
