### ISSUE TITLE
Peer2Peer_Connection Failed on 1.200.027

### ISSUE THREAD

**Issue by Archivist27** [Devidian/docker-spaceengineers#24]
Recently updated to the latest version for the C++ issue after the server updated to the latest version (1.200.027)
Am now running into the Peer2Peer_SessionRequest/ConnectionFailed timeout issue. 

> 2022-02-10 04:43:35.228: Session loaded
> 2022-02-10 04:43:40.834: Game ready...
> 2022-02-10 04:43:48.013: Peer2Peer_SessionRequest [007...758]
> 2022-02-10 04:43:48.013: Peer2Peer_SessionRequest [007...758]
> 2022-02-10 04:44:02.988: Peer2Peer_ConnectionFailed [007...758], Timeout
> 2022-02-10 04:44:03.009: User left [007...758]
> ...
> 2022-02-10 04:45:44.133: Peer2Peer_ConnectionFailed [007...758], Timeout
> 2022-02-10 04:45:44.140: User left [007...758]

Moved my files back to my regular PC, started the server using the dedicated space engineers tool on steam and a friend was able to connect. Copied the files back over for the docker to pick it up, starts fine, but there's a constant connectionfailed for people joining.

**Comment by Devidian** [comment]
i'll check that on my server.

**Comment by Devidian** [comment]
There was a related issue when i tried to use wine staging version, which i resolved by using stable version (6). But stable is now 7 (which was staging before) so maybe i have to force it using wine 6.

**Comment by Devidian** [comment]
I've pinned wine to version 6.0.2 which was working before, hope that helps, worked locally.

**Comment by ryzenpay** [comment]
Hi,
im having this issue again with wine version 9.9, im going to try revert back to 6.0.2 as you said and keep you updated
