### ISSUE TITLE
docker compose up -d ( no ip adress )

### ISSUE THREAD

**Issue by ysm1mh** [Devidian/docker-spaceengineers#25]
hello guys. amazing work on getting this fixed.   BUT i have a small issue.

when i start up the container with 
docker-compose up   then the game starts no issues.

docker-compose up -d    container fails to start.

  D-Bus not built with -rdynamic so unable to print a backtrace
se-ds-docker | wine: Assertion failed at address 00007F94D0499CE1 (thread 0074), starting debugger...
se-ds-docker | 2022-02-10 17:22:14.522: Error: No IP assigned. 

everytime i use -d option it fails IP adress.

what am i doing wrong?

**Comment by Devidian** [comment]
see #19
