### ISSUE TITLE
Any way to safely stop server? Stopping container does not save world

### ISSUE THREAD

**Issue by ScrapyHD** [Devidian/docker-spaceengineers#35]
Is there any way to issue the "taskkill /IM SpaceEngineersDedicated.exe" command in order to stop and save the server before stopping the container. Just stopping the container does not safely stop the server, and because of that every time I stop the container then start it again, the world is rolled back a bit. I'm asking about directly issuing a command to the container since the remote api isn't functional. Thanks!

**Comment by Devidian** [comment]
I dont have an answer to that currently. My server is usually running on a remote vm 24/7 with a 10h restart timer (from the game itself) So i never came up to that Question myself. If there is any, i don't know, but there might also be no way to do so.

As a workaround, wait until next world save before stopping the server.

**Comment by ScrapyHD** [comment]
Can you explain how to setup a restart timer from the game itself? Didn't know that was an option and would work for me. Thanks!

**Comment by Devidian** [comment]
Sure, just look at that screenshot
![image](https://user-images.githubusercontent.com/10413872/213627124-1415c3ea-05d4-4229-8df8-0aee527f9065.png)

When you setup your world you can set restart under 'Maintenance'. If you want to change this on an existing instance you have to open `SpaceEngineers-Dedicated.cfg`

![image](https://user-images.githubusercontent.com/10413872/213627532-eaa14a8d-4b88-4618-8656-330d1b5f8d32.png)

**Comment by ScrapyHD** [comment]
perfect, thanks!

**Comment by dazoe** [comment]
I know this issue is closed and it's old, I use podman instead of docker. but I managed to get podman stop to properly shutdown the server. I added a trap to the entrypoint.sh which sends SIGINT to SpaceEngineersDedicated.exe
I couldn't test building it into an image because when I build the image with podman there is some other issue with the crypto api wine is using.

```shell
# add signal trap handler somewhere near top 
sigtrap() {
        echo "-----SENDING SIGINT TO GAME-----"
        killall -INT SpaceEngineersDedicated.exe
}

#set trap handler, add & to background the wine command, and wait for wine to exit before exiting
trap 'sigtrap' SIGTERM
wine SpaceEngineersDedicated.exe -noconsole -ignorelastsession -path Z:\\appdata\\space-engineers\\instances\\${INSTANCE_NAME} &
wait $!

```
