### ISSUE TITLE
Install / update error

### ISSUE THREAD

**Issue by Roskoov** [Devidian/docker-spaceengineers#38]
Hello, Thanks you for you job but i need some help now :')

When i do the docker compose the image build, no problem
But when it's time to launch the container i got this

![image](https://user-images.githubusercontent.com/84028530/223613811-d806ae21-3cdb-417c-94d4-7fb28f579faa.png)

Install & Update, Update config are empty
The current config is good, i think, i don't see error, and at the end 

![image](https://user-images.githubusercontent.com/84028530/223613992-96a2e737-04d0-4110-b857-943053a75319.png)

I want to see more so i try again the .entrypoint.sh and i got this 

![image](https://user-images.githubusercontent.com/84028530/223614160-1eac5f17-fbd8-493d-961d-2c2e42e29739.png)

So if you have an idea of what is this or what i can do ?
I got other container with steamcmd for other game and i got no problem :(

**Comment by sylvainsf** [comment]
You need to have DedicatedServer64 mounted inside that directory.

**Comment by Roskoov** [comment]
Just update DSM to latest version
