### ISSUE TITLE
Installing the Server

### ISSUE THREAD

**Issue by Padi1111** [Devidian/docker-spaceengineers#43]
Hello,

I've got some small problem understading some steps in the install process.

From where should I be taking those directory from ?

     - /appdata/space-engineers/instances
      - /appdata/space-engineers/SpaceEngineersDedicated
      - /appdata/space-engineers/steamcmd

Thx

**Comment by Padi1111** [comment]
But I dont have a appdata directory, I'm on linux.

**Comment by Devidian** [comment]
Yes sure, `mkdir -p /appdata/space-engineers/`

If you like you can change your local path to anything else existing but then i might not be able to give any more support :D

**Comment by Padi1111** [comment]
Ok I got it to work.

The part that I didn't understand was for SpaceEngineersDedicated & steamcmd.
I thought that I had to import those directory from the windows desktop dedicated server application.
But no, you simply create /appdata/space-engineers/ and those 2 directorys will be created and populated by the docker (If someone else has the same IQ then me and can't figure it out).
