### ISSUE TITLE
Any way to stop server updates?

### ISSUE THREAD

**Issue by re3lex** [Devidian/docker-spaceengineers#47]
Hi,

Is there any way to stop server get SE updates during every container start?

**Comment by Devidian** [comment]
Hi,
you could modify entrypoint.sh with interactive shell login and comment Line 9, but why would you?

**Comment by re3lex** [comment]
hi @Devidian . Thanks for your answer. I will try that approach.

> but why would you?
I setup SE dedicated server in my home LAN to play with my children together. We are using, lets say, "not official SE release" which has lover version than version in Steam and hence than deployed to the server. In this case SE on client PC is not connecting to the server due to version mismatch.
So I just want to freeze version on my SE server.
