### ISSUE TITLE
Usage of the Container

### ISSUE THREAD

**Issue by Sral248** [Devidian/docker-spaceengineers#5]
First of all thanks a lot for this great Docker Container and the example helped a lot. Now I'm at a point where I have the Server up and running but I don't know how to update the map or config without repulling the whole 1.7 GB Image. I'm quite new to docker so probably there is a smarter solution. When I just stop the container to change the config and start it again it doesn't change anything. Hopefully you can give me some advice.

**Comment by Sral248** [comment]
Okay I realized that I edited the wrong config. I changed the SpaceEngineers-Dedicated.cfg and not the cfg for the specific map. But then I don't quit get it why this cfg exists. 
```
 <LoadWorld>Z:\appdata\space-engineers\instances\DockerQuickStart\Saves\Docker Star System</LoadWorld>
```
Is this the only relevant part and the rest gets overwritten when the map is loaded?

**Comment by Devidian** [comment]
Sorry for the late answer. The `SpaceEngineers-Dedicated.cfg` is the config created before a world is initialized and saved. After the first start usually the `Sandbox_config.sbc` is used when it comes to game settings. 

The `SessionSettings` block in `SpaceEngineers-Dedicated.cfg` is copied to the `Settings` block in the `Sandbox_config.sbc`, the other settings of `SpaceEngineers-Dedicated.cfg` are still valid, for example IP, SteamPort, ServerPort, LoadWorld. 

IP and LoadWorld are overwritten on startup of the docker container (`entrypoint.sh`) as these are relevant to the docker container.

If you want to load your own save just upload it to your server /appdata/space-engineers/instances/YOUR_NAME.

Create it by using the server config GUI from the dedicated server and just upload it. YOUR_NAME is then the instance name of your world. Set it in docker-compose.yml and run `docker-compose up -d`, you do not need to repull anything. If its still unclear ask, if you got /get the solution please close this issue.
