### ISSUE TITLE
How to restart server properly

### ISSUE THREAD

**Issue by Arterias1** [Devidian/docker-spaceengineers#52]
Didn't find a way to properly "save & restart" the Space Engineers instance.
Any way to do it since there i since we have no gui/console.

Thanks !

**Comment by Devidian** [comment]
Hey good question, i can't give you a good answer currently as i have never thought about that.
May i ask what the reason is, behind your question? 

I'm fine with auto-restart so far.

**Comment by Arterias1** [comment]
Hi @Devidian thanks for your answer.

I have setup a auto-restart of the container every day at 0200UTC but when it happend, the game didn't performed a save and we lose every work since the last auto-save.

May I ask how you do your auto-restart ?
Didn't find way except docker command with python.

**Comment by Devidian** [comment]
I just use the internal SEDS restart mechanism

![image](https://github.com/Devidian/docker-spaceengineers/assets/10413872/272f29f8-0276-42dc-bb04-ace2e4efd017)

**Comment by Arterias1** [comment]
ahah I feel stupid, totally forgot about that, thanks :)
