### ISSUE TITLE
unable to install winetricks ( permission denied

### ISSUE THREAD

**Issue by ptidoc** [Devidian/docker-spaceengineers#56]
here i write the problem and the solution ( a solution )
on your dockerfil you need to add after the run line for the winetricks.sh this:
`RUN chmod a+rx /root/winetricks.sh &&\
  /root/winetricks.sh && \
`
Save the files and restart the build

**Comment by ptidoc** [comment]
i was a bit in a positiv attitude.... i have it seems authorisations problem. My docker user is well configured ( i've tried to build in root for testing purpose, and always the sames problem. Build of the image is ok but after runing docker run nameofimage i've got this:
`ln: failed to create symbolic link '/root/.steam/root': No such file or directory
ln: failed to create symbolic link '/root/.steam/steam': No such file or directory
Redirecting stderr to '/root/Steam/logs/stderr.txt'
`
`grep: /appdata/space-engineers/instances//SpaceEngineers-Dedicated.cfg: No such file or directory
sed: can't read /appdata/space-engineers/instances//SpaceEngineers-Dedicated.cfg: No such file or directory
grep: /appdata/space-engineers/instances//SpaceEngineers-Dedicated.cfg: No such file or directory
sed: can't read /appdata/space-engineers/instances//SpaceEngineers-Dedicated.cfg: No such file or directory
`

Don't know what i've missed.... help please ? :)

**Comment by Devidian** [comment]
Sorry currently im moving, so i have just a little to no time. I dont know when i can spent time to look into this issue.

**Comment by ptidoc** [comment]
hi and ty for your response. just want to tell that i'm a big noob on docker so maybe i can help u when you'll have time to think about it

First of all i try to launch the docker using docker run + name of the docker . the docker-compose.yml was not read and it's normal i think
After seeing many forum  i decided to run the docker with docker compose up
the steam error disapear but i'm still stuck with the appdata files . All the directories are empty ( no instances etc ... 
trying to do a bad job but chmoded 777 -R all the directory even the dockers files don't solve the problem

for information: i've made a directory with on the top the repository of your work. and created all the folders ( appdata space-engineers plugins instances etc .... 
copy the world with the saves files cleanly renamed 
chmoded the folders in 777 for testing purpose.
Are rerun the docker compose up -d
still the same ( i use an user who are fully autorised to run docker (groupes and all the stuff )

it's seems to be clearly some kind of autorisation but, sorry, i'm an early beginner on docker and it seems that this is not an easy app regarding the lots of man and issues on the docker website itself.

Take care of u and, btw, Happy new year  :) 

![docker_err](https://github.com/Devidian/docker-spaceengineers/assets/156485943/bb9aaa7b-eb18-41a5-b3ac-818bd26b138d)

**Comment by ptidoc** [comment]
problem solved. Use the 12TH issue of this docker page for the solution i've found)

**Comment by ptidoc** [comment]
problem solved. Use the 12TH issue of this docker page for the solution i've found)
