### ISSUE TITLE
Problem with VRage.GameServices.IMyUGCService

### ISSUE THREAD

**Issue by Bulwarini** [Devidian/docker-spaceengineers#57]
I'm trying to run a steam network server, using docker image. 
[_space_logs(1).txt](https://github.com/Devidian/docker-spaceengineers/files/13933014/_space_logs.1.txt)
Here are the logs for docker, it loops out.
[SpaceEngineersDedicated_20240114_20085247.log](https://github.com/Devidian/docker-spaceengineers/files/13933016/SpaceEngineersDedicated_20240114_20085247.log)
and here is space engineers log.

**Comment by ptidoc** [comment]
Hello I recommand to not use the docker devidian image but to build your own one . Devidian do a wonderfull job you just need to use the docker-compose files in the repository file of this docker page. Be sure that you have the BULD: . line and rename the container_namecommand : with yourowname. It appears that your error is probably on dotnet package. and this issue can be solved by updating all of the package you are installing.

i've made a complete procedure in the 12th issue on this docker page for further information. GL HF
