### ISSUE TITLE
the system cannot remove ......

### ISSUE THREAD

**Issue by Janmia2000** [Devidian/docker-spaceengineers#61]
Hey everything works so far, he just can't delete the log files and tries to do this in an endless loop

![Screenshot 2024-05-03 163418](https://github.com/Devidian/docker-spaceengineers/assets/130296801/734ae26d-abb8-4eea-96d6-30b27686776b)

**Comment by Devidian** [comment]
I did not encounter that problem yet. Is it an existing path ?

**Comment by Janmia2000** [comment]
Yes the path exist, for troubleshooting i added it also!

![image](https://github.com/Devidian/docker-spaceengineers/assets/130296801/6898e6c8-1860-4ee4-a244-603770223e2f)

**Comment by Devidian** [comment]
In the log you have `SE-Home` and in the path `SEHome` maybe that's the point ?

**Comment by Janmia2000** [comment]
i edited it but no
I add the complet console output and the compose

![image](https://github.com/Devidian/docker-spaceengineers/assets/130296801/864f700d-da06-4a8f-88a9-77a7cbed089c)

![image](https://github.com/Devidian/docker-spaceengineers/assets/130296801/9cf9d7ac-fab9-4a45-9b38-1820054ed0b4)

**Comment by Janmia2000** [comment]
Hey I find my problem. My Docker permissions had sum issues. Now I have a new problem, he says that my game files are corrupted and I should look in the log but which one?

**Comment by Devidian** [comment]
In most cases the docker log should output what you need to know. In all other cases there should be a more detailed logfile somewhere but im not sure if thats true for the dedicated logfile. You can find it in your instance folder, it should look like
![image](https://github.com/user-attachments/assets/889ecd15-514d-47b4-ab98-1aec2f94c25b)

**Comment by Janmia2000** [comment]
Hey thanks for your work and Support! My last problem is solved, the world folders name was "Star System XXXXX" and the application expactet "Star System" XD
