### ISSUE TITLE
Load checkpoint failed / world not found

### ISSUE THREAD

**Issue by minatsukiyo** [Devidian/docker-spaceengineers#63]
Hi, I keep getting a load checkpoint failed error, I'v ebeen trying for the past 3-4 hours to help resolve this issue, re, creating the server on windblows dedicated server manager and re-uploading it to (what I presume to be) the correct directory.

I have my dockers running just fine for other game servers, just this one doesn't want to, let me break down the directory structure: 
/home/docky/space_engineers_servers/lethal_idiots, I created the /appdata/space-engineers directory's
I then have the docker-compose.yml in the /home/docky/space_engineers_server/lethal_idiots directory.

the attached yml is what I use.
I've tried both with./appdata and without appdata/..., neither seem to work, I've also dropped my instance into the instances directory, and changed the Saves folder to not hold the date, and have the date (as created by the dedicated server manager) so I also checked the
SpaceEngineers-Dedicated.cfg to have or not have the time stamp, I only had 1 Saves folder, or both, but I keep getting issues here. I'm unsure of what I'm actually doing wrong here, can anyone help? Attached you will also fine the latest log file.

 
![image_2024-05-24_223133192](https://github.com/Devidian/docker-spaceengineers/assets/9785782/81cac9ed-2d3c-4e4a-bf67-d14a4dddd4e1)
[docker-compose.yml.txt](https://github.com/Devidian/docker-spaceengineers/files/15439735/docker-compose.yml.txt)

[logs docker compse logs.txt](https://github.com/Devidian/docker-spaceengineers/files/15439783/logs.docker.compse.logs.txt)

[SpaceEngineersDedicated_20240524_203746583.log](https://github.com/Devidian/docker-spaceengineers/files/15439784/SpaceEngineersDedicated_20240524_203746583.log)

**Comment by minatsukiyo** [comment]
I've been trying for a while longer, creating new instances, like Never_surrender and Never, nothing else, so i'm completely clueless.

**Comment by Devidian** [comment]
hmm, never seen before. Did you startup the instances on windows once before transferring to docker?

**Comment by minatsukiyo** [comment]
Yes I made sure to actually load into the instance before I transferred them to the docker container.  I wasn't sure about which save name I should be using in the INSTANCE_NAME=, is this the instance main folder, or the save file name with the date stamp? Were we meant to adjust the save file and cnf file to not have stamps? As the time stamp adds a space and it seems like i get errors when there is a space in the save world file. 

As I'm trying to load the scenario never surrender as a save file, I've noticed it makes a sub directory in the Saves folder, so the structure tree looks like this: Saves/lethal_idiots/Mission01/*.vx2, sandbox_config.sbc ,...

**Comment by Devidian** [comment]
A picture tells more than 1000 words so:
![image](https://github.com/Devidian/docker-spaceengineers/assets/10413872/600a41d6-3364-449c-a87a-49a2884c708d)

in this case Debian is my `INSTANCE_NAME`

**Comment by minatsukiyo** [comment]
In my case, Never_Surrender is my instance name (moved away from the older lethal_idiots a sit got correupted with me changing things in the cfg file: 
![image](https://github.com/Devidian/docker-spaceengineers/assets/9785782/1ec326db-1372-47cb-a27f-78b314a3e599)

**Comment by Devidian** [comment]
You have 2 instances, one is named `Neder_surrender` (your open folder) and the other is `Never_Surrender` (the closed folder) be sure to select the correct, case sensitive!
I hope you adjusted your paths if you use docker compose as you have your `appdata` not in the root!

**Comment by minatsukiyo** [comment]
I definitely adjusted the paths to be ./appdata.... and yes I had the case sensitivity wrong at one point, just seems i forgot to remove the wrong one

**Comment by minatsukiyo** [comment]
Maybe I'm going at this all wrong, but, I'd want to start from a fresh setup to try again. Can you check if my steps are correct on what I think I should be doing?

1. Create a new directory where all the host files will be: /home/docky/space_engineers_servers/new_setup
  1.1 make director's appdata & space-engineers
2. Create a new docker-compse.yml adn edit the location .appdata/space-engineers/... (and new name of instance, no spaces)
3. On Windows machine, opend dedicated server manager
4. Create a new instance
5. Choose never surrender mission
6. Adjust config, with adjusted port.
7. Start the new instance
8. Stop the new instance
9. Copy the files from c:/programdata/SpaceEngineersDedicated/instances/new_setup
10. winscp to place them in the instance under appdata/space-engineers/instances
11. Start the docker?

At point 12 I'm not sure, is this correct? The save file in the directory has the date added to it, and last time it struggled with this, and it's in a subfolder called missions 01, is this correct or should this work?
Just typing this while at work as I'm thinking of trying these steps when I get back.

I'll have to test if it works with a regular star system as well, see if the issues in with the fact that this is a scenario instead of a regular star system.

**Comment by jgradzki** [comment]
Yeap, I changed folder `instances/MyInstance/Save/My Save <some date>/` to `instances/MyInstance/Save/My Save/` (removed date) and it worked

**Comment by Devidian** [comment]
So, we can close this issue?
