### ISSUE TITLE
get the game save

### ISSUE THREAD

**Issue by ryzenpay** [Devidian/docker-spaceengineers#64]
Hey, in your documentation you mentioned: "(detailed instructions follow when requested)" for getting the game save for the initial setup.

When using the space engineers dedicated server tool, going to the `%appdata%/spaceengineersdedicatedserver/` folder, i see nothing of "instance" or "plugin".

Am i looking in the wrong place or am i just completely wrong?

**Comment by Devidian** [comment]
![image](https://github.com/Devidian/docker-spaceengineers/assets/10413872/c6655518-5c59-4282-a7c0-5c676673e500)

you have to look in `Roaming`

**Comment by ryzenpay** [comment]
i understand, thats where i am, but i see nothing of "instances", "steamcmd", or "plugins" <- just mods.

by "instances" do you mean that entire folder, and is the "steamcmd" just a folder which has steamcmd.exe in it and the update .exe?

Thanks for the response

**Comment by ryzenpay** [comment]
after letting the docker run without any of my configuration i think i finally understood.

the way i got it working: let the docker do one run before it fails and restarts, it will fill in the folders + download the game.
Then copy over the Saves from your Saves made when running the Dedicated Server Tool on ur pc, same with the .cfg config overwriting that one which the docker made. Then let it run again and it will start up perfectly.
I guess it was just the lack of documentation that threw me off searching for these folders but i got it working now.

Thank you,
Good luck to anyone trying to make it work
