### ISSUE TITLE
How to use SteamCMD / Update the Server?

### ISSUE THREAD

**Issue by DocEverdream** [Devidian/docker-spaceengineers#7]
Hi, first of all, thx for this amazing thing :)
I managed to play with a friend on the server since todays update of SE.

now i would like to update the server inside this container, but i can't manage it.
It looks like there should be an auto-update, but it seems like there is no connection possible. But i havn't changed anything, and steam has installed the server a few days ago...

Log Output:

-------------------------------START------------------------------
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
FS_stat on file ./public/steambootstrapper_english.txt which appeared to exist failed!!!
[----] Verifying installation...
[  0%] Downloading Update...
[  0%] !!! Fatal Error: Steamcmd needs to be online to update.	 Please confirm your network connection and try again.
/data/src/tier0/threadtools.cpp (3658) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x58929d70/0x0xf73a3b'
preloader: Warning: failed to reserve range 00010000-00110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
preloader: Warning: failed to reserve range 0000000000010000-0000000000110000
2020-12-10 18:12:46.785: App Version: 01_197_069
2020-12-10 18:12:46.810: Is official: True [NO][NIS][NAMP]
2020-12-10 18:12:46.812: Environment.ProcessorCount: 8
2020-12-10 18:12:46.815: Environment.OSVersion: Microsoft Windows 7 Professional (Microsoft Windows NT 6.1.7601 Service Pack 1)

**Comment by CrypticSafe5** [comment]
In the server config for the instance, did you try turning the auto update feature on?

**Comment by CrypticSafe5** [comment]
Try turning the auto update on in the instance's server config and rebuilding the container.

**Comment by DocEverdream** [comment]
ahm sry, where?

**Comment by DocEverdream** [comment]
Hm i edited the cfg and rebuilded the container, but there seems no effect at all..

**Comment by DocEverdream** [comment]
Bad News, just a serverreboot with same log as above...

**Comment by DocEverdream** [comment]
Just startet a ping for 205.196.6.172 client-download.steampowered.com.
On my host machine i'll get a response, inside the container no response... 
But i can't get any idea whats wrong with the container

**Comment by DocEverdream** [comment]
solved it, but i still don't know what was wrong. i just deleted everything and recrated it from scratch. but now everything updates and can connect. strange... Anyway, i'll close this issue
