### ISSUE TITLE
When Ingame Scripts are enabled the server closes just after loading the session

### ISSUE THREAD

**Issue by Curucma** [Devidian/docker-spaceengineers#70]
My Server runs fine, i wanted to enable ingame scripts in an existing game. I enabled ingame scripts in the /appdata/intances/saves in the Sandbox_config.sbc. When i start my server then the server stops after a few seconds:
se-ds-docker  | 2024-08-15 19:56:38.114: Session loaded
se-ds-docker  | 2024-08-15 19:56:39.441: Game ready...
se-ds-docker  | -----------------------------------END GAME----------------------------------
se-ds-docker  | -----------------------------------BYE !!!!----------------------------------
se-ds-docker exited with code 0

Do i miss soemthing maybe i have to enable ingame scripts somewhere else as well. 
Thanks for ur great work allready !

**Comment by Curucma** [comment]
It was an Problem with an specific Script Isys Inventory Managment. Seems to be an memory with wine

**Comment by Devidian** [comment]
Ok good to know, glad you found the problem. Maybe the next wine version will fix it or not.
