### ISSUE TITLE
Save Naming/Server Crash

### ISSUE THREAD

**Issue by japietru2004** [Devidian/docker-spaceengineers#8]
Does save need any special name? I get in log:
2020-12-19 17:44:25.358 - Thread:   1 ->  MySandboxGame.Constructor() - END
2020-12-19 17:44:25.359 - Thread:   1 ->  Server Name: 
2020-12-19 17:44:25.361 - Thread:   1 ->  World Name: 
2020-12-19 17:44:25.420 - Thread:   1 ->  Auto Restart Enabled
2020-12-19 17:44:25.433 - Thread:   1 ->  MySandboxGame.Initialize() - START
and it crashes server.
World is in docker_folder_path/diff/appdata/space-engineers/instances/Saves
Do I need to place SpaceEngineers-Dedicated.cfg in instances folder too?

**Comment by japietru2004** [comment]
Seams like server has started after I added SpaceEngineers-Dedicated.cfg, could you add in setup to copy SpaceEngineers-Dedicated.cfg to /instances and save to /instances/Saves and change path to save in config?

**Comment by Devidian** [comment]
First of all, how did you start the docker container? It looks like you did something "wrong" on startup

**Comment by japietru2004** [comment]
well
first error I have solved I just added .cfg of server to /instance

**Comment by japietru2004** [comment]
I have got to this structure
![obraz](https://user-images.githubusercontent.com/51274570/102699541-d645b000-4245-11eb-9360-69d52f0e00b8.png)

**Comment by Devidian** [comment]
![image](https://user-images.githubusercontent.com/10413872/102699572-0f7e2000-4246-11eb-977b-3bdb7bfca109.png)
![image](https://user-images.githubusercontent.com/10413872/102699587-215fc300-4246-11eb-9356-11bd754d9aee.png)
It should look like this. The SpaceEngineers-Dedicated.cfg is always in an instance created by the Windows GUI.

If you start the docker via docker-compose all ports should work. If you start it via docker command you must pass in all stuff that is setup in the compose file by hand.

**Comment by japietru2004** [comment]
![obraz](https://user-images.githubusercontent.com/51274570/102699657-afd44480-4246-11eb-9abd-7598f79ddb4d.png)
something might be broken - this is what I see default - I added 27016/udp self

**Comment by japietru2004** [comment]
I started server via cockpit

**Comment by Devidian** [comment]
what is this? I cant read this. What is cockpit?

**Comment by japietru2004** [comment]
well all above are settings provided by docker file - https://cockpit-project.org/

**Comment by japietru2004** [comment]
and sr if you can't read - some text on screens is in my lang - PL

**Comment by japietru2004** [comment]
klucz - key
wartość- value

**Comment by Devidian** [comment]
Oh i see cockpit is some docker admin tool, ok but i cant help here as i dont know how to setup my docker with cockpit.

**Comment by japietru2004** [comment]
I know how to setup cockpit stuff
my problem is that I can't connect to server

**Comment by japietru2004** [comment]
port 27016 is open on firewall and on docker

**Comment by Devidian** [comment]
yeha, and i can tell you that the port part is in the compose file, dont know how to set this up on cockpit :)

**Comment by japietru2004** [comment]
well I add here log of server
[SpaceEngineersDedicated_20201219_211314728.log](https://github.com/Devidian/docker-spaceengineers/files/5720153/SpaceEngineersDedicated_20201219_211314728.log)

**Comment by Devidian** [comment]
Maybe its just incompatible with cockpit, if so im sorry! currently i dont have time to try it myself with cockpit, maybe next year

**Comment by japietru2004** [comment]
do I need to worry about steam port ?

**Comment by Devidian** [comment]
if you use a firewall, yeah might be an issue

**Comment by japietru2004** [comment]
I try this - bottom post - https://www.reddit.com/r/spaceengineers/comments/4g17cv/dedicated_server_ports/

**Comment by japietru2004** [comment]
erm ok so it seams SE wiiki is outdated - it is need to use 2716 tcp and udp for server

**Comment by japietru2004** [comment]
and if you could update setup guide on here git - please;
I mean telloing to coppy generated SpaceEngineers-Dedicated.cfg to /instance and save file to /instance/Saves folder + tell to use 27016 tcp and udp

**Comment by Devidian** [comment]
the setup guide is correct for normal usage. You dont need the `SpaceEngineers-Dedicated.cfg` in `instances` because in the docker-compose you set the `INSTANCE_NAME=yournameofinstancehere` and it will look up the config there. Also the 27016 port (you need only udp) is setup there.

**Comment by japietru2004** [comment]
well I was able to join server after using also tcp port (mayby you can tell disclaimer to tell to try use udp and tcp if you can't connect server)

**Comment by japietru2004** [comment]
I thinked bit and I know that simply only udp should work but this could be good ass added (anyway issue can be closed)


[COCKPIT]
add port 27016 from docker to host twice, udp and tcp
[JOIN ISSUE]
try this solution https://www.reddit.com/r/spaceengineers/comments/4g17cv/dedicated_server_ports/
